workspace "BossEngine"
	architecture "x64"
	startproject "Game"

	configurations
	{
		"Debug",
		"Release",
		"Distribution"
	}

-- output directory name
	
outputDir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

-- include directory relative to folder
IncludeDir = {}
IncludeDir["GLFW"] = "BossEngine/Externals/GLFW/include"
IncludeDir["Glad"] = "BossEngine/Externals/Glad/include"
IncludeDir["ImGui"] = "BossEngine/Externals/imgui"
IncludeDir["glm"] = "BossEngine/Externals/glm"
IncludeDir["stb_image"] = "BossEngine/Externals/stb_image"

include "BossEngine/Externals/GLFW"
include "BossEngine/Externals/Glad"
include "BossEngine/Externals/imgui"


-------------------------------------------------------------------------------------
------------------------ Engine project ---------------------------------------------	
-------------------------------------------------------------------------------------

-- This is Engine VS Project creation.
project "BossEngine"
	location "BossEngine"	-- folder location name
	kind "StaticLib"		-- set to sharedLib for dll.
	language "C++"
	cppdialect "C++17"
	staticruntime "on"

	targetdir ("bin/" .. outputDir .. "/%{prj.name}")	-- this for the output of .exe file.
	objdir ("obj/" .. outputDir .. "/%{prj.name}")		-- the output of .obj file generated by scripts.
	
	-- precompile header
	pchheader "bepch.h"
	pchsource "BossEngine/Source/bepch.cpp"
	
	-- take the whole file inside project
	files
	{
		"%{prj.name}/Source/**.h",
		"%{prj.name}/Source/**.cpp",
		"%{prj.name}/Externals/stb_image/**.cpp",
		"%{prj.name}/Externals/stb_image/**.h",
		"%{prj.name}/Externals/glm/glm/**.hpp",		
		"%{prj.name}/Externals/glm/glm/**.inl"		
	}
	
	defines
	{
		"_CRT_SECURE_NO_WARNINGS"
	}
	
	-- include external libs.
	includedirs
	{
		"%{prj.name}/Source",
		"%{prj.name}/Externals/spdlog/include",
		"%{IncludeDir.GLFW}",
		"%{IncludeDir.Glad}",
		"%{IncludeDir.ImGui}",
		"%{IncludeDir.glm}",
		"%{IncludeDir.stb_image}"
	}
	
	links
	{
		"GLFW",
		"Glad",
		"ImGui",
		"opengl32.lib"
	}
	
	filter "system:windows"
		systemversion "latest"
		
		-- Linking input definition.
		defines
		{
			"BE_PLATFORM_WINDOWS",
			"BE_BUILD_DLL"
		}
				
-- filter configuration of VS
	filter "configurations:Debug"
		defines "BE_DEBUG"
		runtime "Debug"
		symbols "on"
	
	filter "configurations:Release"
		defines "BE_RELEASE"
		runtime "Release"
		optimize "on"
	
	filter "configurations:Distribution"
		defines "BE_DIST"
		runtime "Release"
		optimize "on"	
		
		
-------------------------------------------------------------------------------------
------------------------ Game project -----------------------------------------------		
-------------------------------------------------------------------------------------
		
project "Game"
	location "Game"
	kind "ConsoleApp"	
	language "C++"
	cppdialect "C++17"
	staticruntime "on"
	
	targetdir ("bin/" .. outputDir .. "/%{prj.name}")
	objdir ("obj/" .. outputDir .. "/%{prj.name}")

	files
	{
		"%{prj.name}/Source/**.h",
		"%{prj.name}/Source/**.cpp"	
	}
	
	-- including all External libs + Engine
	includedirs
	{
		"BossEngine/Externals/spdlog/include",
		"BossEngine/Source",
		"BossEngine/Externals",
		"%{IncludeDir.glm}"
	}
	
	-- Add linking to the engine so the game can use Engine API.
	links
	{
		"BossEngine"
	}
	
	filter "system:windows"
		systemversion "latest"
		
	defines
	{
		"BE_PLATFORM_WINDOWS"
	}
		
-- filter configuration of VS
	filter "configurations:Debug"
		defines "BE_DEBUG"
		runtime "Debug"
		symbols "on"
	
	filter "configurations:Release"
		defines "BE_RELEASE"
		runtime "Release"
		optimize "on"
	
	filter "configurations:Distribution"
		defines "BE_DIST"
		runtime "Release"
		optimize "on"	